[package]
name = "kernel-xdp-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13", features = ["async_support"] }
aya-log = "0.2"

[[bin]]
name = "xdp_pattern_match"
path = "src/main.rs"
