[package]
name = "userspace-xdp-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya_bpf = { version = "0.1", features = ["bindings"] }
aya_log_ebpf = "0.1"

[[bin]]
name = "xdp_redirect"
path = "src/main.rs"
