[package]
name = "kernel-xdp"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13", features = ["async_support"] }
aya-log = "0.2"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
